# Generated by Django 2.2.12 on 2022-01-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('branch', models.CharField(max_length=60)),
                ('reg_no', models.IntegerField(verbose_name=40)),
                ('roll_no', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='users')),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
