# Generated by Django 2.2.12 on 2022-01-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daksh', '0002_auto_20220122_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Member',
        ),
    ]
